name: helium-browser # CHANGE THIS to your registered snap name
base: core24
version: '0.0.1' 
summary: Private, fast, and honest web browser
description: |
  Helium is a bullshit-free web browser based on Chromium.
  It is designed to be fast, private, and honest.

grade: stable
confinement: strict
license: GPL-3.0

website: https://github.com/imputnet/helium-linux
source-code: https://github.com/imputnet/helium-linux


parts:
  helium:
    plugin: dump
    source: https://github.com/imputnet/helium-linux/releases/latest
    source-type: tar
    
    # Fix directory structure (move files from subdir to root)
    override-build: |
      craftctl default
      find $SNAPCRAFT_PART_INSTALL -mindepth 2 -maxdepth 2 -name "helium" -exec mv {}/../* $SNAPCRAFT_PART_INSTALL/ \;
      find $SNAPCRAFT_PART_INSTALL -type d -empty -delete

    # The "Kitchen Sink" list for Chromium dependencies on Ubuntu 24.04 (Core24)
    stage-packages:
      # Core Chromium Dependencies
      - libnss3
      - libnspr4
      - libasound2t64
      - libxss1
      - xdg-utils
      - libgbm1
      - libgtk-3-0
      - libx11-xcb1
      - libxcb-dri3-0
      - libatspi0t64  # <--- UPDATED: 't64' suffix added for Core24
      - libdrm2
      
      # Graphics & Hardware Acceleration (Vulkan/OpenGL)
      - libvulkan1
      - mesa-vulkan-drivers
      - libgl1
      - libegl1
      - libgl1-mesa-dri
      
      # Codecs and Media
      - libffmpeg-nvenc-dev 
      
      # Hardware Integration
      - libu2f-udev
      - libpci3
      
      # Fonts (Crucial for rendering web pages correctly)
      - fonts-noto
      - fonts-noto-color-emoji
      - fonts-liberation
      - fontconfig
      - libfontconfig1