name: helium-browser # CHANGE THIS to your registered snap name
base: core24
version: '0.0.1' 
summary: Private, fast, and honest web browser based on Chromium
description: |
  Helium is a bullshit-free web browser based on Chromium.
  It is designed to be fast, private, and honest.
  Based on the AUR package configuration.

grade: stable
confinement: strict
license: GPL-3.0-only AND BSD-3-Clause

website: https://github.com/imputnet/helium-linux
source-code: https://github.com/imputnet/helium-linux
issues: https://github.com/imputnet/helium-linux/issues

# Platforms are injected automatically by main.yml

apps:
  helium:
    command: helium
    extensions: [gnome]
    common-id: helium.desktop
    plugs:
      - network
      - network-bind
      - audio-playback
      - audio-record
      - camera
      - opengl
      - x11
      - wayland
      - browser-support
      - removable-media
      - home
      - desktop
      - desktop-legacy
      - unity7
      - screen-inhibit-control
      - cups-control
      - joystick
      - password-manager-service
      - u2f-devices
      - raw-usb
      - upower-observe

parts:
  helium:
    plugin: dump
    source: https://github.com/imputnet/helium-linux/releases/latest
    source-type: tar
    
    # --- FIXED BUILD LOGIC ---
    override-build: |
      craftctl default
      
      echo "Listing extracted files for debugging..."
      ls -F $SNAPCRAFT_PART_INSTALL
      
      # The tarball extracts into a folder named like 'helium-0.7.9.1-x86_64_linux/'
      # We move everything from that folder to the install root so Snapcraft can find 'helium'
      cp -r $SNAPCRAFT_PART_INSTALL/helium-*_linux/* $SNAPCRAFT_PART_INSTALL/
      
      # Remove the duplicate directory to clean up
      rm -rf $SNAPCRAFT_PART_INSTALL/helium-*_linux/
      
      # Make sure the binary is executable
      chmod +x $SNAPCRAFT_PART_INSTALL/helium
    # -------------------------

    stage-packages:
      - libgtk-3-0
      - libnss3
      - libnspr4
      - libasound2t64
      - libxss1
      - xdg-utils
      - libcups2t64
      - libgcrypt20
      - libpulse0
      - libpci3
      - libffi8
      - libva2
      - libva-drm2
      - libva-x11-2
      - mesa-va-drivers
      - libgbm1
      - libdrm2
      - libvulkan1
      - mesa-vulkan-drivers
      - libgl1
      - libegl1
      - libgl1-mesa-dri
      - fonts-liberation
      - fonts-noto
      - fonts-noto-color-emoji
      - fontconfig
      - libfontconfig1
      - libu2f-udev