name: helium-browser
base: core24
version: '0.0.1' 
summary: Private, fast, and honest web browser
description: |
  Helium is a bullshit-free web browser based on Chromium.
  It is designed to be fast, private, and honest.

grade: stable
confinement: strict
license: GNU General Public License v3.0
website: https://helium.computer
source-code: https://github.com/imputnet/helium-linux


apps:
  helium:
    command: helium
    extensions: [gnome]
    plugs:
      - network
      - network-bind
      - audio-playback
      - opengl
      - x11
      - wayland
      - browser-support
      - removable-media
      - home
      - desktop
      - desktop-legacy
      - unity7
      - camera

parts:
  helium:
    plugin: dump
    source: https://github.com/imputnet/helium-linux/releases/latest
    source-type: tar
    
    override-build: |
      craftctl default
      find $SNAPCRAFT_PART_INSTALL -mindepth 2 -maxdepth 2 -name "helium" -exec mv {}/../* $SNAPCRAFT_PART_INSTALL/ \;
      find $SNAPCRAFT_PART_INSTALL -type d -empty -delete
    stage-packages:
      - libnss3
      - libnspr4
      - libasound2t64
      - libxss1
      - xdg-utils
      - libgbm1
      - libgtk-3-0
      - libvulkan1
      - libgl1
      - libegl1
      - libu2f-udev