name: helium-browser
base: core24
version: '0.0.1'
summary: Private, fast, and honest web browser
description: |
  Helium is a bullshit-free web browser based on Chromium.
  It is designed to be fast, private, and honest.

grade: stable
confinement: strict

apps:
  helium:
    command: helium
    extensions: [gnome]
    plugs:
      - network
      - network-bind
      - audio-playback
      - opengl
      - x11
      - wayland
      - browser-support
      - removable-media

parts:
  helium:
    plugin: dump
    # The workflow will update this URL based on the architecture (x86 or arm)
    source: https://github.com/imputnet/helium-linux/releases/latest
    source-type: tar
    stage-packages:
      - libnss3
      - libnspr4
      - libasound2t64
      - libxss1
      - xdg-utils