name: helium-browser
base: core24
version: '0.0.1' 
summary: Private, fast, and honest web browser based on Chromium
description: |
  Helium is a bullshit-free web browser based on Chromium.
  It is designed to be fast, private, and honest.
grade: stable
confinement: strict
license: GPL-3.0-only AND BSD-3-Clause
title: Helium Browser
website: https://helium.computer
source-code: https://github.com/imputnet/helium-linux
issues: https://github.com/imputnet/helium-linux/issues
contact: https://x.com/heliumbrowser
donation: https://helium.computer/sponsor

platforms:
  amd64:
  arm64:

apps:
  helium:
    command: usr/bin/helium
    extensions: [gnome]
    desktop: usr/share/applications/helium.desktop
    common-id: helium.desktop
    plugs:
      - network
      - network-bind
      - audio-playback
      - audio-record
      - camera
      - opengl
      - x11
      - wayland
      - browser-support
      - removable-media
      - home
      - desktop
      - desktop-legacy
      - unity7
      - screen-inhibit-control
      - cups-control
      - joystick
      - password-manager-service
      - u2f-devices
      - raw-usb
      - upower-observe

parts:
  helium:
    plugin: dump
    source: https://github.com/imputnet/helium-linux/releases/latest
    source-type: tar
    build-packages:
      - wget
    override-build: |
      craftctl default
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/bin
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/share/applications
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/share/pixmaps
      wget https://raw.githubusercontent.com/imputnet/helium/main/resources/branding/app_icon/raw.png -O $SNAPCRAFT_PART_INSTALL/usr/share/pixmaps/helium.png
      find $SNAPCRAFT_PART_INSTALL -name "helium.desktop" -exec mv {} $SNAPCRAFT_PART_INSTALL/usr/share/applications/ \;
      DESKTOP="$SNAPCRAFT_PART_INSTALL/usr/share/applications/helium.desktop"
      sed -i 's|^Icon=.*|Icon=helium|g' "$DESKTOP"
      sed -i 's|^Exec=.*|Exec=helium %U|g' "$DESKTOP"
      cat <<EOF > $SNAPCRAFT_PART_INSTALL/usr/bin/helium
      #!/bin/sh
      exec "\$SNAP/chrome" --no-sandbox --disable-dev-shm-usage "\$@"
      EOF
      chmod +x $SNAPCRAFT_PART_INSTALL/usr/bin/helium
      chmod +x $SNAPCRAFT_PART_INSTALL/chrome
    stage-packages:
      - libnss3
      - libnspr4
      - libasound2t64
      - libcups2t64
      - libpci3
      - libu2f-udev
      - libva2
      - libva-drm2
      - libva-x11-2
      - mesa-va-drivers
      - libvulkan1
      - mesa-vulkan-drivers
      - fonts-liberation
      - fonts-noto
      - fonts-noto-color-emoji
      - fontconfig
      - libfontconfig1