name: helium-browser
base: core22
version: '0.0.1' 
summary: Private, fast, and honest web browser
description: Helium is a bullshit-free web browser based on Chromium.
grade: stable
confinement: strict

apps:
  helium:
    command: helium
    extensions: [gnome]
    plugs:
      - network
      - network-bind
      - audio-playback
      - opengl
      - x11
      - wayland
      - browser-support
      - removable-media

parts:
  helium:
    plugin: dump
    source: https://github.com/imputnet/helium-linux/releases/latest
    source-type: tar
    stage-packages:
      - libnss3
      - libnspr4
      - libasound2
      - libxss1
      - xdg-utils